# Generated by Django 5.2.4 on 2026-02-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_rules',
            old_name='element_id',
            new_name='element',
        ),
    ]
